Repository hoprnet/hopr-devrel, pull requests merged in 2022-01, with the labels that each got.

#141 update stake's README
  stake/README.md
Labels: documentation

#142 unlock tokens and NFTs
  stake/packages/frontend/components/StakeXHoprTokens.tsx
  stake/packages/frontend/lib/reducers.ts
  stake/yarn.lock
Labels: enhancement

#147 Merge stake v1 unlock to stake v2
  stake/packages/frontend/components/StakeXHoprTokens.tsx
  stake/packages/frontend/lib/reducers.ts
  stake/packages/frontend/public/Surveyor/bronze
  stake/packages/frontend/public/Surveyor/diamond
  stake/packages/frontend/public/Surveyor/gold
  stake/packages/frontend/public/Surveyor/silver
Labels: enhancement

#150 fix unlock button
  stake/packages/frontend/components/StakeXHoprTokens.tsx
  stake/packages/frontend/package.json
  stake/packages/frontend/yarn.lock
  yarn.lock
Labels: bug

#153 text changes
  stake/packages/frontend/components/layout/Layout.tsx
  stake/packages/frontend/pages/index.tsx
Labels: enhancement

#151 use local timezone
  stake/packages/frontend/components/NFTQuery.tsx
  stake/packages/frontend/components/StakeXHoprTokens.tsx
Labels: enhancement

#148 Support HoprStake2
  stake/packages/frontend/components/NFTQuery.tsx
  stake/packages/frontend/components/atoms/TotalStakedBalance.tsx
  stake/packages/frontend/lib/addresses.ts
  stake/packages/frontend/lib/connectors.ts
  stake/packages/frontend/lib/hooks.ts
  stake/packages/frontend/lib/reducers.ts
  stake/packages/frontend/package.json
  stake/yarn.lock
Labels: enhancement

#161 Stake v1/update unlock text
  stake/packages/frontend/components/StakeXHoprTokens.tsx
  stake/packages/frontend/pages/index.tsx
Labels: enhancement

#162 stake-s1: make some text bold
  stake/packages/frontend/pages/index.tsx
Labels: enhancement

#152 subgraph for stake season 2
  subgraph/packages/subgraph-stake-s2/.env.sample
  subgraph/packages/subgraph-stake-s2/.gitignore
  subgraph/packages/subgraph-stake-s2/README.md
  subgraph/packages/subgraph-stake-s2/abis/HoprBoost.json
  subgraph/packages/subgraph-stake-s2/abis/HoprStake2.json
  subgraph/packages/subgraph-stake-s2/config/goerli.json
  subgraph/packages/subgraph-stake-s2/config/local.json
  subgraph/packages/subgraph-stake-s2/config/xdai.json
  subgraph/packages/subgraph-stake-s2/docker-compose.yaml
  subgraph/packages/subgraph-stake-s2/package.json
  subgraph/packages/subgraph-stake-s2/schema.graphql
  subgraph/packages/subgraph-stake-s2/src/library.ts
  subgraph/packages/subgraph-stake-s2/src/mapping.ts
  subgraph/packages/subgraph-stake-s2/subgraph.template.yaml
  subgraph/packages/subgraph-stake-s2/yarn.lock
Labels: analytics
